{% set name = "lovely-numpy" %}
{% set version = "0.2.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5bcaeaea6e9163673146e6df2a0601bf0e7a8951af1665bfada778376752549e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy >=1.17
    - fastcore
    - matplotlib-base

test:
  imports:
    - lovely_numpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-numpy
  summary: 💟 Lovely numpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xl0
    - sugatoray
