{% set name = "lovely-numpy" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lovely-numpy-{{ version }}.tar.gz
  sha256: 397e250f8448ed68302bfd9a22b73e96b51d0fd4b95c596d5ce7b965a0212579

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.17
    - fastcore
    - ipython
    - matplotlib-base

test:
  imports:
    - lovely_numpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-numpy
  summary: 💟 Lovely numpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xl0
    - sugatoray
