{% set name = "lovely-numpy" %}
{% set version = "0.2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1a326732eeea9bcaae606af4e7d740dbb12cb2fec98cd46b0f188d9b705d8da1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy >=1.17
    - fastcore
    - matplotlib-base

test:
  imports:
    - lovely_numpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-numpy
  summary: 💟 Lovely numpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xl0
    - sugatoray
