{% set name = "lovely-numpy" %}
{% set version = "0.2.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c414db415701f060c0875cd1d8013a7167664f95e85d11644fdff646941abdb0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy >=1.17
    - fastcore
    - matplotlib-base

test:
  imports:
    - lovely_numpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-numpy
  summary: 💟 Lovely numpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xl0
    - sugatoray
