{% set name = "lovely-numpy" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ed56660986731db3d3d7ff130e85e8d162e96c96042a0bd9a3992d32a3b34e2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.17
    - fastcore
    - ipython
    - matplotlib-base

test:
  imports:
    - lovely_numpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xl0/lovely-numpy
  summary: 💟 Lovely numpy
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xl0
    - sugatoray
